name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Build with VitePress
        run: npm run docs:build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: docs/.vitepress/dist

  deploy-firebase:
    name: Deploy to Firebase Hosting
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository  # Critical for firebase.json
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4  # Use stable version
        with:
          name: dist
          path: dist  # Built files now in ./dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting  # Point to downloaded files
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
